-- 기존 데이터 삭제
DELETE FROM seats;
DELETE FROM reading_rooms;

-- 새로운 방 데이터 삽입
INSERT INTO reading_rooms (name, floor) VALUES
('2층 1열람실', 2),
('2층 1노트북열람실', 2),
('2층 새벽별당', 2),
('4층 2노트북열람실', 4),
('4층 3열람실', 4);

-- 2층 1열람실 (357석)
INSERT INTO seats (room_id, seat_number, status) 
SELECT 1, n, 'USABLE' FROM (
  SELECT @row := @row + 1 as n FROM 
  (SELECT 1 UNION SELECT 2 UNION SELECT 3 UNION SELECT 4 UNION SELECT 5) t1,
  (SELECT 1 UNION SELECT 2 UNION SELECT 3 UNION SELECT 4 UNION SELECT 5) t2,
  (SELECT 1 UNION SELECT 2 UNION SELECT 3 UNION SELECT 4 UNION SELECT 5) t3,
  (SELECT 1 UNION SELECT 2 UNION SELECT 3 UNION SELECT 4 UNION SELECT 5) t4,
  (SELECT 1 UNION SELECT 2 UNION SELECT 3 UNION SELECT 4 UNION SELECT 5) t5,
  (SELECT 1 UNION SELECT 2 UNION SELECT 3 UNION SELECT 4 UNION SELECT 5) t6,
  (SELECT 1 UNION SELECT 2 UNION SELECT 3) t7,
  (SELECT @row:=0) init
) nums WHERE n <= 357;

-- 2층 1노트북열람실 (188석)
INSERT INTO seats (room_id, seat_number, status) 
SELECT 2, n, 'USABLE' FROM (
  SELECT @row := @row + 1 as n FROM 
  (SELECT 1 UNION SELECT 2 UNION SELECT 3 UNION SELECT 4 UNION SELECT 5) t1,
  (SELECT 1 UNION SELECT 2 UNION SELECT 3 UNION SELECT 4 UNION SELECT 5) t2,
  (SELECT 1 UNION SELECT 2 UNION SELECT 3 UNION SELECT 4 UNION SELECT 5) t3,
  (SELECT 1 UNION SELECT 2 UNION SELECT 3 UNION SELECT 4 UNION SELECT 5) t4,
  (SELECT 1 UNION SELECT 2 UNION SELECT 3) t5,
  (SELECT @row:=0) init
) nums WHERE n <= 188;

-- 2층 새벽별당 (215석)
INSERT INTO seats (room_id, seat_number, status) 
SELECT 3, n, 'USABLE' FROM (
  SELECT @row := @row + 1 as n FROM 
  (SELECT 1 UNION SELECT 2 UNION SELECT 3 UNION SELECT 4 UNION SELECT 5) t1,
  (SELECT 1 UNION SELECT 2 UNION SELECT 3 UNION SELECT 4 UNION SELECT 5) t2,
  (SELECT 1 UNION SELECT 2 UNION SELECT 3 UNION SELECT 4 UNION SELECT 5) t3,
  (SELECT 1 UNION SELECT 2 UNION SELECT 3 UNION SELECT 4 UNION SELECT 5) t4,
  (SELECT 1 UNION SELECT 2 UNION SELECT 3 UNION SELECT 4) t5,
  (SELECT @row:=0) init
) nums WHERE n <= 215;

-- 4층 2노트북열람실 (372석)
INSERT INTO seats (room_id, seat_number, status) 
SELECT 4, n, 'USABLE' FROM (
  SELECT @row := @row + 1 as n FROM 
  (SELECT 1 UNION SELECT 2 UNION SELECT 3 UNION SELECT 4 UNION SELECT 5) t1,
  (SELECT 1 UNION SELECT 2 UNION SELECT 3 UNION SELECT 4 UNION SELECT 5) t2,
  (SELECT 1 UNION SELECT 2 UNION SELECT 3 UNION SELECT 4 UNION SELECT 5) t3,
  (SELECT 1 UNION SELECT 2 UNION SELECT 3 UNION SELECT 4 UNION SELECT 5) t4,
  (SELECT 1 UNION SELECT 2 UNION SELECT 3) t5,
  (SELECT @row:=0) init
) nums WHERE n <= 372;

-- 4층 3열람실 (572석)
INSERT INTO seats (room_id, seat_number, status) 
SELECT 5, n, 'USABLE' FROM (
  SELECT @row := @row + 1 as n FROM 
  (SELECT 1 UNION SELECT 2 UNION SELECT 3 UNION SELECT 4 UNION SELECT 5) t1,
  (SELECT 1 UNION SELECT 2 UNION SELECT 3 UNION SELECT 4 UNION SELECT 5) t2,
  (SELECT 1 UNION SELECT 2 UNION SELECT 3 UNION SELECT 4 UNION SELECT 5) t3,
  (SELECT 1 UNION SELECT 2 UNION SELECT 3 UNION SELECT 4 UNION SELECT 5) t4,
  (SELECT 1 UNION SELECT 2 UNION SELECT 3 UNION SELECT 4 UNION SELECT 5) t5,
  (SELECT 1 UNION SELECT 2 UNION SELECT 3) t6,
  (SELECT @row:=0) init
) nums WHERE n <= 572;

-- 확인
SELECT r.id, r.name, r.floor, COUNT(s.id) as seat_count FROM reading_rooms r LEFT JOIN seats s ON r.id = s.room_id GROUP BY r.id;
